1  numpy数组的整数索引与切片  数组切片是原始数组视图（这就意味着，如果做任何修改，原始都会跟着更改）,如果不想改变，就使用.copy

In [1]:
import numpy as np

1.1 通过索引或切片来访问和修改

In [ ]:
a = np.arange(0,25,5)

In [ ]:
a

In [ ]:
a[3] #利用整数索引获取单个元素

In [ ]:
a[2:5]  #获取切片

In [ ]:
a[2:8:3]

In [ ]:
a[::-2]

In [ ]:
for i in a:
    print(i*(1/2.0),end=',')

1.2 二维numpy数组的切片与切块

In [ ]:
def f(x,y):
    return 10*x + y

In [ ]:
b = np.fromfunction(f,(4,5),dtype=float)  #给定每个轴的大小

In [ ]:
b

In [ ]:
b[2,3]

In [ ]:
b[0:2,1]

In [ ]:
b[:4,3]

In [ ]:
b[1:3,:]

In [ ]:
b[-1] #只指定了一个轴，另一个轴默认为所有。

In [ ]:
b[-1] = 0

In [ ]:
b[-1]

1.3 Iterating over multidimensional arrays is done with respect to the first axis

In [ ]:
b.shape

In [ ]:
for row in b:
    print(row)

In [ ]:
type(row)

In [ ]:
for element in b.flat:  #flat为array的属性
    print(element)

In [ ]:
b

2 高级索引

2.1 整数数组索引

In [ ]:
a = np.arange(10)*2

In [ ]:
a

In [ ]:
i = np.array([2,2,3,7,6])  #索引为一组数组 ，花式索引

In [ ]:
a[i] 

In [ ]:
j = np.array([[3, 4], [9, 7]]) #索引为二维数组,索引的形状就是结果的形状

In [ ]:
a[j]

（2） 二维数组的整数数组索引

In [ ]:
a = np.arange(12).reshape(3,4) #值数组是二维

In [ ]:
a

In [ ]:
i = np.array([[0, 1],   #提供第一个维度的索引,行索引
              [1, 2]])  

In [ ]:
a[i]

In [ ]:
j = np.array([[2, 1],       #提供第二个维度的索引,列索引
               [3, 3]])

a[i,j]     #(i,j)成为一对元组，去索引数据

l = (i,j)

l

In [ ]:
a[l]

In [ ]:
（3） 使用一个数组去索引另一个数组

In [ ]:
x = np.array([[4,2,3], [1,0,3]])
index_array = np.argmax(x, axis=-1)

In [ ]:
index_array

In [ ]:
np.expand_dims(index_array, axis=-1) #index_array为需要增加维度数组，axis为增加新轴的位置 

In [ ]:
np.take_along_axis(x, np.expand_dims(index_array, axis=-1), axis=-1)   

In [ ]:
np.take_along_axis(x, np.expand_dims(index_array, axis=-1), axis=-1).squeeze(axis=-1)

2.3 使用布尔数组进行索引，布尔索引通过布尔运算（如：比较运算符）来获取符合指定条件的元素的数组,产生新数组

In [ ]:
a = np.arange(20).reshape(4,5)

In [ ]:
a

In [ ]:
b = a % 3 == 0

In [ ]:
b

In [ ]:
a[b]  #产生新数组

In [ ]:
a[b] = a[b]*2

In [ ]:
a

（2） 对于数组的每一个维度，给定一个一维布尔索引数组用以选择需要的切片

In [ ]:
a = np.arange(12).reshape(3,4)

In [ ]:
b1 = np.array([False,True,True])    

In [ ]:
b1

In [ ]:
b2 = np.array([True,False,True,False])  

In [ ]:
a[b1,b2]

In [ ]:
a

Boolean array indexing
A single boolean index array is practically identical to x[obj.nonzero()]

In [ ]:
a

In [ ]:
如果要提取列索引,则可以使用np.where

In [ ]:
# any和all测试布尔型数组，对于非布尔型数组，所有非0元素将会被当做True
dataSet = np.array([[ 0, -1, -2, -3, 181, 5451, 0, 0, 8, 8, 1, 9, 9, 1, 0.11, 0, 0 ],
                    [ 0, -1, -2, -3, 181, 5451, 0, 0, 8, 8, 1, 9, 9, 1, 0, 0, 0 ],
                    [ 0, -1, -2, -3, 181, 0,    0, 0, 8, 8, 1, 9, 9, 1, 0.11, 0, 0 ]])


In [ ]:
nonZero = dataSet[:, np.any(dataSet, axis=0)]

In [ ]:
nonZero

In [ ]:
np.any(dataSet, axis=0)

In [ ]:
nonZero

In [ ]:
np.all(dataSet, axis=0)

In [ ]:
nonZeroall = dataSet[:, np.any(dataSet, axis=0)]

In [ ]:
nonZeroall

In [ ]:
np.where(~dataSet.any(axis=0))

2.4 花式索引指的是利用整数数组进行索引。

花式索引根据索引数组的值作为目标数组的某个轴的下标来取值。对于使用一维整型数组作为索引，如果目标是一维数组，那么索引的结果就是对应位置的元素；如果目标是二维数组，那么就是对应下标的行。
花式索引的结果，以一个特定的顺序排列。而这个顺序，就是我们所传入的整数列表或者ndarray。这也为我们以特定的顺序来选取数组子集，提供了思路。


In [ ]:
(1) 传入顺序索引数组

In [ ]:
x=np.arange(32).reshape((8,4))
print(x[[4,2,1,7]])

In [ ]:
x

In [ ]:
(2) 传入倒序索引数组

In [ ]:
x=np.arange(15).reshape((3,5))
print(x[[-1,-2,-3]])

案例：

In [ ]:
mycolor = np.array([[0, 0, 0],         # black
  [255, 0, 0],       # red
  [0, 255, 0],       # green
  [0, 0, 255],       # blue
  [255, 255, 255]])  # white


In [ ]:
picture = np.array([[0, 1, 2, 0],        # each value corresponds to a color in the palette
                   [0, 3, 4, 0]])


In [ ]:
mycolor[picture]

In [ ]:
mycolor.shape

(3) 传入多个索引数组（要使用np.ix_） 

In [ ]:
x=np.arange(32).reshape((8,4))

In [ ]:
x

In [ ]:
np.ix_([1,5,7,2],[0,3,1,2])

In [ ]:
print(x[np.ix_([1,5,7,2],[0,3,1,2])])

In [ ]:
(4) ix_函数 生成一个索引器

In [2]:

a = np.array([2,3,4,5])
b= np.array([8,5,4])
c = np.array([5,4,6,8,3])

In [3]:
ax,bx,cx = np.ix_(a,b,c)

In [4]:
ax

array([[[2]],

       [[3]],

       [[4]],

       [[5]]])

In [5]:
bx

array([[[8],
        [5],
        [4]]])

In [6]:
cx

array([[[5, 4, 6, 8, 3]]])

In [7]:
ax.shape,bx.shape,cx.shape

((4, 1, 1), (1, 3, 1), (1, 1, 5))

In [8]:
result = ax + bx * cx

In [9]:
result.shape

(4, 3, 5)

In [10]:
result

array([[[42, 34, 50, 66, 26],
        [27, 22, 32, 42, 17],
        [22, 18, 26, 34, 14]],

       [[43, 35, 51, 67, 27],
        [28, 23, 33, 43, 18],
        [23, 19, 27, 35, 15]],

       [[44, 36, 52, 68, 28],
        [29, 24, 34, 44, 19],
        [24, 20, 28, 36, 16]],

       [[45, 37, 53, 69, 29],
        [30, 25, 35, 45, 20],
        [25, 21, 29, 37, 17]]])

In [11]:
result[3,2,4]

17

In [12]:
a[3]+b[2]*c[4]

17

In [ ]:
x=np.arange(32).reshape((8,4))


In [ ]:
x

In [ ]:
np.ix_([1,5,7,2],[0,3,1,2])

In [ ]:
np.ix_([1,5,7,2],[0,3,1,2],[0,1,5,6])

In [ ]:
print (x[np.ix_([1,5,7,2],[0,3,1,2])])

利用idx_实现reduce功能

In [ ]:
def ufunc_reduce(ufct, *vectors):
   vs = np.ix_(*vectors)
   r = ufct.identity
   for v in vs:
       r = ufct(r,v)
   return r


In [ ]:
a = np.array([2,3,4,5])

In [ ]:
b = np.array([8,5,4])

In [ ]:
c = np.array([5,4,6,8,3])

In [ ]:
ufunc_reduce(np.add,a,b,c)

In [ ]:
ufunc_reduce(np.add,a,b,c).shape

3 案例：求5个时间序列中最大值位置和序列

In [13]:
time = np.linspace(10,100,10)  #时间点

In [14]:
time

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [15]:
data = np.sin(np.arange(50).reshape(10,5))

In [16]:
data

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736],
       [ 0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836],
       [-0.13235175,  0.76255845,  0.95637593,  0.27090579, -0.66363388],
       [-0.98803162, -0.40403765,  0.55142668,  0.99991186,  0.52908269],
       [-0.42818267, -0.99177885, -0.64353813,  0.29636858,  0.96379539],
       [ 0.74511316, -0.15862267, -0.91652155, -0.83177474,  0.01770193],
       [ 0.85090352,  0.90178835,  0.12357312, -0.76825466, -0.95375265]])

In [17]:
ind = data.argmax(axis = 0 ) #获得最大值出现的位置

In [18]:
ind

array([4, 9, 5, 6, 2], dtype=int64)

In [19]:
time_max = time[ind] #使用数组进行索引，获得出现最大值的时间点

In [20]:
time_max  #在特定时间序列中，出现最大值的时间点

array([ 50., 100.,  60.,  70.,  30.])

In [21]:
data_max = data[ind,range(data.shape[1])]

In [22]:
data_max

array([0.91294525, 0.90178835, 0.95637593, 0.99991186, 0.99060736])

In [ ]:
data.shape[1]

In [23]:
np.all(data_max == data.max(axis=0))   

True