In [1]:
import numpy as np

In [2]:
import numpy.random as nr

In [3]:
a = np.floor(100*nr.random((4,5)))

In [4]:
a

array([[58.,  0., 20., 31., 49.],
       [11., 52.,  8., 85., 27.],
       [ 1., 78., 21., 68., 67.],
       [ 4., 37.,  4., 40., 34.]])

In [5]:
a.shape

(4, 5)

1 数组改变形状

In [6]:
a.reshape(5,4)  #返回是新的数组，没有改变原数组

array([[58.,  0., 20., 31.],
       [49., 11., 52.,  8.],
       [85., 27.,  1., 78.],
       [21., 68., 67.,  4.],
       [37.,  4., 40., 34.]])

In [7]:
a

array([[58.,  0., 20., 31., 49.],
       [11., 52.,  8., 85., 27.],
       [ 1., 78., 21., 68., 67.],
       [ 4., 37.,  4., 40., 34.]])

In [8]:
a.T   #返回的新数组，没有改变原数组

array([[58., 11.,  1.,  4.],
       [ 0., 52., 78., 37.],
       [20.,  8., 21.,  4.],
       [31., 85., 68., 40.],
       [49., 27., 67., 34.]])

In [9]:
a.T.shape

(5, 4)

In [10]:
a

array([[58.,  0., 20., 31., 49.],
       [11., 52.,  8., 85., 27.],
       [ 1., 78., 21., 68., 67.],
       [ 4., 37.,  4., 40., 34.]])

In [11]:
a.resize((2,10)) #resize 改变的对象自身

In [12]:
a

array([[58.,  0., 20., 31., 49., 11., 52.,  8., 85., 27.],
       [ 1., 78., 21., 68., 67.,  4., 37.,  4., 40., 34.]])

In [ ]:
a

In [ ]:
a.reshape(4,-1) #-1 代表此轴的大小自动计算所得

In [ ]:
a

2 数组堆叠

In [13]:
a = np.floor(10*nr.random((3,3)))

In [14]:
a

array([[1., 3., 2.],
       [3., 9., 7.],
       [9., 7., 8.]])

In [15]:
b = np.floor(10*nr.random((3,3)))

In [16]:
b

array([[1., 3., 2.],
       [7., 0., 7.],
       [3., 3., 3.]])

In [17]:
np.vstack((a,b))   #纵向拼接，增加样本量

array([[1., 3., 2.],
       [3., 9., 7.],
       [9., 7., 8.],
       [1., 3., 2.],
       [7., 0., 7.],
       [3., 3., 3.]])

In [18]:
np.hstack((a,b))  #横向拼接，增加特征量

array([[1., 3., 2., 1., 3., 2.],
       [3., 9., 7., 7., 0., 7.],
       [9., 7., 8., 3., 3., 3.]])

In [19]:
np.hstack((a,b)).shape

(3, 6)

3 数组分为几个小的数组

In [20]:
a = np.floor(100*nr.random((2,12)))

In [21]:
a

array([[52., 23., 86., 86., 76., 77., 22., 84., 50., 93., 71., 13.],
       [ 9., 23., 42., 17., 15., 17., 68., 45., 58., 34., 85., 40.]])

In [22]:
np.hsplit(a,3) 

[array([[52., 23., 86., 86.],
        [ 9., 23., 42., 17.]]), array([[76., 77., 22., 84.],
        [15., 17., 68., 45.]]), array([[50., 93., 71., 13.],
        [58., 34., 85., 40.]])]

In [23]:
np.hsplit(a,(3,5)) #在数组a的第3索引前和第5索引前切割



[array([[52., 23., 86.],
        [ 9., 23., 42.]]), array([[86., 76.],
        [17., 15.]]), array([[77., 22., 84., 50., 93., 71., 13.],
        [17., 68., 45., 58., 34., 85., 40.]])]

In [24]:
a = np.floor(100*nr.random((12,2)))

In [25]:
np.vsplit(a,3)

[array([[50., 55.],
        [84., 22.],
        [25., 32.],
        [91.,  7.]]), array([[87., 90.],
        [12., 59.],
        [ 1., 66.],
        [27., 52.]]), array([[16., 73.],
        [38.,  6.],
        [62., 54.],
        [79., 54.]])]

In [26]:
np.vsplit(a,(3,4))   #在数组a的第3索引前和第4索引前切割

[array([[50., 55.],
        [84., 22.],
        [25., 32.]]), array([[91.,  7.]]), array([[87., 90.],
        [12., 59.],
        [ 1., 66.],
        [27., 52.],
        [16., 73.],
        [38.,  6.],
        [62., 54.],
        [79., 54.]])]